
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: configmapsecret-manager
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.k8s.mz.com
  resources:
  - configmapsecrets
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.k8s.mz.com
  resources:
  - configmapsecrets/finalizers
  - configmapsecrets/status
  verbs:
  - get
  - patch
  - update
